export const FETCH_USER_ASSESSMENT_DATA = 'FETCH_USER_ASSESSMENT_DATA'
export const  FETCH_USER_ASSESSMENT_SUCCESS ='FETCH_USER_ASSESSMENT_SUCCESS'
export const FETCH_USER_ASSESSMENT_FAILURE = 'FETCH_USER_ASSESSMENT_FAILURE'